import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import StyledComponentsRegistry from "./registry";
import { ThemeProviderNext } from "@/context/ThemeProvider";
import GlobalStyle from "@/assets/styles/globalStyles";
import Header from "@/components/header/header";
import { GlobalProvider } from "@/context/GlobalContext";
import { ReactQueryProvider } from "@/hooks/ProductQuery";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MKS SISTEMAS - LOJA",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ReactQueryProvider>
    <html lang="pt-BR">
      <body className={font.className}>
        <GlobalProvider>
          <StyledComponentsRegistry>
            <ThemeProviderNext>
              <GlobalStyle />
              <Header />
              {children}
            </ThemeProviderNext>
          </StyledComponentsRegistry>

        </GlobalProvider>
      </body>
    </html>
    </ReactQueryProvider>
  );
}
